### ISSUE TITLE
Simplify permissions

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#107]
@FatalEagle finds it too hard to grant permissions to users because they are really vague. For example, `rejudge_submission` only actually lets you rejudge problems that you can edit.

**Comment by Xyene** [comment]
Bug: edit all public problems conflicts with edit own problems: if the former is set, the latter is nulled.

@awaykened @quantum5

**Comment by quantum5** [comment]
Permissions are now properly organized into groups. Perhaps a fixture can be provided for other people to copy. In the end though, the system is now perfectly usable.

**Comment by Xyene** [comment]
The fixture should definitely be provided, specifically since this is a public repo as much as it is a tracker for things that interest the official install.

**Comment by quantum5** [comment]
```yaml
- model: auth.group
  fields:
    name: Problem Setter
    permissions:
    - [add_logentry, admin, logentry]
    - [add_languagelimit, judge, languagelimit]
    - [change_languagelimit, judge, languagelimit]
    - [delete_languagelimit, judge, languagelimit]
    - [add_problem, judge, problem]
    - [change_problem, judge, problem]
    - [edit_own_problem, judge, problem]
    - [add_problemclarification, judge, problemclarification]
    - [change_problemclarification, judge, problemclarification]
    - [delete_problemclarification, judge, problemclarification]
    - [add_problemtranslation, judge, problemtranslation]
    - [change_problemtranslation, judge, problemtranslation]
    - [delete_problemtranslation, judge, problemtranslation]
    - [add_solution, judge, solution]
    - [change_solution, judge, solution]
    - [delete_solution, judge, solution]
    - [rejudge_submission, judge, submission]
- model: auth.group
  fields:
    name: Contest Organizer
    permissions:
    - [add_logentry, admin, logentry]
    - [add_contest, judge, contest]
    - [edit_own_contest, judge, contest]
    - [add_contestproblem, judge, contestproblem]
    - [change_contestproblem, judge, contestproblem]
    - [delete_contestproblem, judge, contestproblem]
    - [add_problem, judge, problem]
    - [change_problem, judge, problem]
    - [edit_own_problem, judge, problem]
- model: auth.group
  fields:
    name: Blogger
    permissions:
    - [add_blogpost, judge, blogpost]
    - [change_blogpost, judge, blogpost]
- model: auth.group
  fields:
    name: Blog Admin
    permissions:
    - [add_blogpost, judge, blogpost]
    - [change_blogpost, judge, blogpost]
    - [delete_blogpost, judge, blogpost]
    - [edit_all_post, judge, blogpost]
- model: auth.group
  fields:
    name: External Problems
    permissions:
    - [change_manually_managed, judge, problem]
- model: auth.group
  fields:
    name: Problem Maintainer
    permissions:
    - [edit_public_problem, judge, problem]
- model: auth.group
  fields:
    name: Comment Moderator
    permissions:
    - [change_comment, judge, comment]
- model: auth.group
  fields:
    name: Rejudger
    permissions:
    - [rejudge_submission_lot, judge, submission]
- model: auth.group
  fields:
    name: Problem Admin
    permissions:
    - [clone_problem, judge, problem]
    - [edit_all_problem, judge, problem]
    - [see_private_problem, judge, problem]
    - [resubmit_other, judge, submission]
    - [view_all_submission, judge, submission]
- model: auth.group
  fields:
    name: Contest Admin
    permissions:
    - [contest_rating, judge, contest]
    - [delete_contest, judge, contest]
    - [edit_all_contest, judge, contest]
    - [see_private_contest, judge, contest]
- model: auth.group
  fields:
    name: Organization Admin
    permissions:
    - [add_organization, judge, organization]
    - [change_organization, judge, organization]
    - [delete_organization, judge, organization]
    - [edit_all_organization, judge, organization]
    - [edit_organization_slots, judge, organization]
    - [organization_admin, judge, organization]
```
