### ISSUE TITLE
Fancier pagination

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#168]
The pagination control was styled a year ago and no more thought went into it. Should be improved.

Ajax and history API should be used when available to spare a page load. Font awesome loading icon should be shown while it loads.

**Comment by Xyene** [comment]
A potential design:

![](https://sc-cdn.scaleengine.net/i/0bcbe402b92b2248721907c53dcc6028.png)

**Comment by FatalEagle** [comment]
Looks out of place.

**Comment by Xyene** [comment]
A more table-like design, since pagination is usually shown next above/below tabular data:

![](https://sc-cdn.scaleengine.net/i/41e88c2301d41e5df2a9a00a98b26b24.png)

**Comment by Xyene** [comment]
Properly justified:

![](https://sc-cdn.scaleengine.net/i/b1144c938351c8fc7eaa57b1154f924a.png)

**Comment by Xyene** [comment]
Relevant styles: 

```css
.pagination a{
	display:inline-block;
	text-decoration:none;
	padding:2px 8px;
	margin-right:5px;
	color:#000;
	border:1px solid #D4D4D4;
	background: none repeat scroll 0% 0% rgba(0, 0, 0, 0.02);
}

.pagination a:hover{
	color:#000;
	background:rgba(0,0,0,.1);
}

.pagination a.active-page{
	color:#FFF;
	background:#2980b9;
	border:1px solid #0bf;
}
```

**Comment by quantum5** [comment]
Created fancier pagination control based on bootstrap:

![](http://i.imgur.com/ReqvpET.png)

```css
ul.pagination {
    display: inline-block;
    padding-left: 0px;
    margin: 0;
    border-radius: 4px;
}

ul.pagination > li {
    display: inline;
}

ul.pagination > li:first-child > a, ul.pagination > li:first-child > span {
    margin-left: 0px;
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
}

ul.pagination > li:last-child > a, ul.pagination > li:last-child > span {
    margin-left: 0px;
    border-top-right-radius: 4px;
    border-bottom-right-radius: 4px;
}

ul.pagination > li > a, ul.pagination > li > span {
    position: relative;
    float: left;
    padding: 6px 12px;
    margin-left: -1px;
    line-height: 1.42857;
    color: #337AB7;
    text-decoration: none;
    background-color: #FFF;
    border: 1px solid #DDD;
}

ul.pagination > .disabled > a, ul.pagination > .disabled > a:focus, ul.pagination > .disabled > a:hover, ul.pagination > .disabled > span, ul.pagination > .disabled > span:focus, ul.pagination > .disabled > span:hover {
    color: #777;
    cursor: not-allowed;
    background-color: #FFF;
    border-color: #DDD;
}

ul.pagination > .active > a, ul.pagination > .active > a:focus, ul.pagination > .active > a:hover, ul.pagination > .active > span, ul.pagination > .active > span:focus, ul.pagination > .active > span:hover {
    color: #FFF;
    cursor: default;
    background-color: #337AB7;
    border-color: #337AB7;
}
```

```html
<ul class="pagination">
    <li class="disabled"><span>&laquo;</span></li>
    <li class="active"><a href="https://dmoj.ca/submissions/">1</a>
    <li><a href="https://dmoj.ca/submissions/2">2</a></li>
    <li><a href="https://dmoj.ca/submissions/3">3</a></li>
    <li><a href="https://dmoj.ca/submissions/4">4</a></li>
    <li><a href="https://dmoj.ca/submissions/5">5</a></li>
    <li><a href="https://dmoj.ca/submissions/6">6</a>
    <li class="disabled"><span>...</span></li>
    <li><a href="https://dmoj.ca/submissions/1699">1699</a></li>
    <li><a href="https://dmoj.ca/submissions/1700">1700</a></li>
    <li><a href="https://dmoj.ca/submissions/2">&raquo;</a></li>
</ul>
```

Refs #205 @Xyene

**Comment by Xyene** [comment]
Darker pagination theme (also Bootstrap based):

![!!!](https://sc-cdn.scaleengine.net/i/ba94aaec9c4edfb4245056bd137f7290.png)

```css
ul.pagination {
    display: inline-block;
    padding-left: 0px;
    margin: 0;
    border-radius: 4px;
}
ul.pagination > li {
    display: inline;
}
ul.pagination > li:first-child > a,
ul.pagination > li:first-child > span {
    margin-left: 0px;
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
}
ul.pagination > li:last-child > a,
ul.pagination > li:last-child > span {
    margin-left: 0px;
    border-top-right-radius: 4px;
    border-bottom-right-radius: 4px;
}
ul.pagination > li > a,
ul.pagination > li > span {
    position: relative;
    float: left;
    padding: 8px 12px;
    line-height: 1.42857;
    text-decoration: none;
    color: #FFF;
    background-color: rgba(0, 0, 0, 0.77);
    border: 1px solid #282828;
    margin-left: -1px;
}
ul.pagination > .disabled > a,
ul.pagination > .disabled > a:focus,
ul.pagination > .disabled > a:hover,
ul.pagination > .disabled > span,
ul.pagination > .disabled > span:focus,
ul.pagination > .disabled > span:hover {
    color: #888;
    background-color: rgba(0, 0, 0, 0.77);
    border-color: #282828;
}
ul.pagination > .active > a,
ul.pagination > .active > a:focus,
ul.pagination > .active > a:hover,
ul.pagination > .active > span,
ul.pagination > .active > span:focus,
ul.pagination > .active > span:hover {
    z-index: 2;
    color: #FFF;
    background-color: #2980B9;
    border-color: transparent;
    cursor: default;
}
```

Also got rid of the `cursor: not-allowed` since it looked out of place. It's a little tall though.
