### ISSUE TITLE
Improved language selection

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#196]
The current dropdown solution won't work for long at the rate with which we're adding new languages. Two ideas:

* select2 dropdown
* ideone-like box

I personally think the latter option would look and work best.

**Comment by quantum5** [comment]
Personally I think select2 is rather painful to setup and loads in too much JS than a custom rolled solution, not to say that the inability to see all languages on one screen is bothersome.

**Comment by FatalEagle** [comment]
Or, we could sort languages in descending order of usefulness. That way scrolling is a non-issue.

**Comment by Xyene** [comment]
Demo:

![](https://sc-cdn.scaleengine.net/i/e4d8f9e880f0bdd90cfd058d118816e2.png)

```css
#language li {
  list-style: none;
}

#language {
  margin:0;
  background:#fefefe;
  padding:8px;
  border:1px solid #2980B9;
  border-radius:4px;
}

#id_language {
  margin:0;
  padding:0;
  list-style-type: none;
  -moz-columns: 5 0px;
}

#id_language li {
  color: #757575;
}

#language-details {
  text-align: right;
  display:block;
  color: #757575;
  font-size:1.2em;
  
}

#id_language li:hover {
  text-decoration: underline;
  color: #252525;
}

#id_language li[selected="selected"] {
  color:black;
  font-weight: bold;
}
```
