### ISSUE TITLE
Compiler messages may be too long

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#276]
<https://dmoj.ca/submission/99051>

![](https://sc-cdn.scaleengine.net/i/53febe883b48a664666cb3ff31e0ad5a1.png)

**Comment by Xyene** [comment]
Two solutions:

```css
pre { white-space: pre-wrap; }
```

```css
pre { overflow-x: scroll; }
```
