### ISSUE TITLE
Line links for submission sources

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#285]
Like https://dmoj.ca/src/110827#line-4.

**Comment by quantum5** [comment]
```css
.source-ln a::before {
    display: block;
    content: " ";
    margin-top: -50px;
    height: 50px;
    visibility: hidden;
}
```
