### ISSUE TITLE
New runtime template

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#289]
![](https://sc-cdn.scaleengine.net/i/ac573b8a7f4eb6a928cc3d6c8055980c.png)

Saves the need to click through to view info.

**Comment by Xyene** [comment]
Hacked style:

```css
.table td:nth-child(4) {
  text-align: left;
}

.table td:nth-child(4) .content-description {
  margin-top: -1em;
  margin-bottom: -1em;
}

.table td {
  text-align: left;
}

.table td:nth-child(3), .table th:nth-child(3) {
  display: none;
}
```
