### ISSUE TITLE
Mobile navigation bar

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#349]
@Xyene's new `wpadmin` styled user info moves onto the menu instead of staying on the top bar.

**Comment by quantum5** [comment]
A work in progress:

```html
<div id="user-links" style="height: 100%">
  <ul style="display: block; margin: 0">
    <li style="display: block; height: 100%">
      <a href="/user" style="display: block; padding: 0px; height: 100%">
        <span style="font-size: 13px; height: 36px; padding-top: 8px; display: block">
          <img src="//www.gravatar.com/avatar/3aac760f3f17effb1202af33ca70bb9f?d=identicon&amp;s=32" style="vertical-align: middle; border-radius: 6px; display: inline; margin-right: 6px; margin-top: 2px; margin-left: 5px;" height="24" width="24">
          <span style="color: rgb(238, 238, 238); vertical-align: middle; display: inline; margin-top: 11px; padding: 0px; margin-right: 9px;">
            Hello,&nbsp;<b>quantum</b>.
          </span>
        </span>
      </a>
      <ul style="width: 150px">
        <li><a href="/admin/" class="user-opt">Admin</a></li>
        <li><a href="/edit/profile/" class="user-opt">Edit profile</a></li>
        <li><a href="/accounts/logout/?next=" class="user-opt">Log out</a></li>
      </ul>
    </li>
  </ul>
</div>
```

```css
#user-links {
    top: 0;
    right: 0;
    position: absolute;
    color: #5c5954;
}

#user-links li {
    text-transform: none;
}

@media (max-width: 760px) {
    #user-links > ul > li > a > span {
        padding-top: 4px !important;
        height: 32px !important;
    }

    #user-links > ul > li > ul {
        left: 0 !important;
        margin-top: 0 !important;
    }
}
```

Mobile nav rules must now be `#nav-list` instead of `#navigation ul`.
