### ISSUE TITLE
help!  ProbableAuthenticationError

### ISSUE THREAD

**Issue by hiyot** [DMOJ/site#407]
Hello guys,
I tried to install your awesome project. And Via the docs and the issues, I solved most problems occured. But when ProbableAuthenticationError raised, I spent much time but still can not solve it :(

Below are my settings
	in local_settings.py
		JUDGE_AMQP_PATH = 'amqp://guest:guest@localhost:5672/vhost' # yes, I do create a virtual host named vhost and ensure guest privileged
	in /etc/rabbitmq/enabled_plugins
		[rabbitmq_auth_backend_http,rabbitmq_management].
	in /etc/rabbitmq/rabbitmq.config
		[
		{rabbit, [
		{auth_backends, [rabbit_auth_backend_internal, rabbit_auth_backend_http]}
		]},
		{rabbitmq_auth_backend_http, [
		{user_path, "http://localhost:8000/api/judge/auth/rabbitmq/user"},
		{vhost_path, "http://localhost:8000/api/judge/auth/rabbitmq/vhost"},
		{resource_path, "http://localhost:8000/api/judge/auth/rabbitmq/resource"}
		]}
		]. 
	the rabbitmq version is 3.5.4
	I also added a judge named ExampleJudge and added its key in the admin panel

below are my commands 
	python manage.py runserver localhost:8000
	python manage.py runamqpd
	python main.py amqp://localhost:5672/vhost -c ./sample_judge_conf.yml

Thank you:)

**Comment by quantum5** [comment]
There is not enough information to make a meaningful response.

But let me guess. Did you restart RabbitMQ after you changed the configuration? Did you perhaps added the key with the quotes in the admin? If so, it helps that the key remain unquoted in the admin.

**Comment by hiyot** [comment]
Now, the judge connected the site correctly, ExampleJudge is online now.
It turned out that I forgot to 'python manage.py compilemessages' :(

But still, when I create a problem, click the submit solution button, it appears 'No judge is available for this problem.'. What should I do next?

**Comment by Xyene** [comment]
Awesome!

For a problem to be submitable, you must have data in the correct format placed where the judge is checking for problem data - `problem_storage_root`. If `problem_storage_root` is a list, it will add all problems in the subdirectories of every item; if it is a single string, it will add all problems in the subdirectories of _that_ subdirectory. The exact logic is given [here](https://github.com/DMOJ/judge/blob/master/judgeenv.py#L85).

Essentially if you were to add `aplusb` to the site, your filesystem structure would look like:

```
+ problem_storage_root (whatever you defined in the judge conf)
   + aplusb
      + aplusb.zip
      + init.json
```

If you have `watchdog` (`pip install watchdog`) installed, the judge will notify the site of any problem updates. If you don't, you'll have to restart the judge to see any effect.

**Comment by hiyot** [comment]
watchdog installed, aplusb problem folders and files added, and the problem ramains :(
should I take some actions in 'admin panel/language' , or with judge/judge.py ?

**Comment by Xyene** [comment]
Could you please post the relevant part of your judge config yml, as well as the outputs of `tree` in the problem storage root? Also, just to confirm: you see the judge as online on your equivalent of <https://dmoj.ca/status>, right?

**Comment by hiyot** [comment]
1.filetree
```
hiyot@hiyot-Lenovo:~/Github$ ls -R judge/problems/
judge/problems/:
aplusb

judge/problems/aplusb:
aplusb.zip  init.json
```

2.sample_judge_conf.yml
```
# This is the same ID you specified in the judge admin panel
id: ExampleJudge
# The key this judge will use to authenticate with the site server, generated from the admin panel
key: "-t_qBN}_zr@WF_O(j>A]9:JR,-]@FMPN38(9Y:CDD]`ZT.|dYdH03q#;cN8?5s(gvu0LeSBMy3cc;06)pF)<nX]C=.Us^{#7w!9:"
# Where to look for problems on the local filesystem.
# This directory /not/ scanned recursively, and any directory containing an init.json file is assumed to
# be a problem directory.
problem_storage_root:
  - problems
# All configuration for language executors
# If you're unsure of what values a language needs, your best bet is to consult the source of the executor:
# <https://github.com/DMOJ/judge/tree/master/executors>
runtime:
  ccl: /opt/ccl/lx86cl
  sed: /bin/sed
  awk: /usr/bin/awk
  gnatmake: /usr/bin/gnatmake
  chicken-csc: /usr/bin/csc
  dart: /opt/dart-sdk/bin/dart
  tclsh: /usr/bin/tclsh
  cobc: /usr/bin/cobc
  erl: /usr/bin/erl
  erlc: /usr/bin/erlc
  tprolog: /opt/turing/tprolog/tprolog
  tprologc: /opt/turing/tprolog/tprologc
  turing_dir: /opt/turing/tprolog
  node: /usr/bin/node
  lua: /usr/bin/lua
  ocaml: /usr/bin/ocamlopt
  pypy: /opt/pypy/bin/pypy
  pypydir: /opt/pypy/
  pypy3: /opt/pypy3/bin/pypy
  pypy3dir: /opt/pypy3/
  ghc: /usr/bin/ghc
  go: /usr/bin/go
  fsharpc: /usr/bin/fsharpc
  mono-csc: /usr/bin/mono-csc
  mono-vbnc: /usr/bin/vbnc
  mono: /usr/bin/mono
  dmd: /usr/bin/dmd
  fpc: /opt/fpc-2.6.4/bin/fpc
  clang: /usr/bin/clang
  clang++: /usr/bin/clang++
  gcc: /usr/bin/gcc
  g++: /usr/bin/g++
  g++11: /usr/bin/g++
  g++14: /opt/gcc-5.1.0/bin/g++
  gfortran: /usr/bin/gfortran
  nasm: /usr/bin/nasm
  ld: /usr/bin/ld
  python: /opt/python27/bin/python2.7
  python2dir: /opt/python27/
  python3: /opt/python34/bin/python3.4
  python3dir: /opt/python34/
  java: /usr/bin/java
  javac: /usr/bin/javac
  java8: /usr/lib/jvm/jdk-8-oracle-i586/bin/java
  javac8: /usr/lib/jvm/jdk-8-oracle-i586/bin/javac
# Custom V8 build to facilitate online judging: https://github.com/DMOJ/v8dmoj
  v8dmoj: /home/judge/judge/executors/v8dmoj
  php: /usr/bin/php
  phpconfdir: /etc/php5/
  perl: /usr/bin/perl
  ruby19: /usr/bin/ruby1.9.1
  ruby21: /usr/bin/ruby
  racket: /opt/racket/bin/racket
  raco: /opt/racket/bin/raco
  racket-lib: /opt/racket/lib
  gnustep-config: /usr/bin/gnustep-config
  gobjc: /usr/bin/gcc
```

3.ExampleJudge is confirmed online again.

**Comment by Xyene** [comment]
Ah, there's the problem: `problem_storage_root` should contain absolute paths, but you are passing a relative path to `problems`.

**Comment by hiyot** [comment]
when I set problem_storage_root:/home/hiyot/Github/judge/problems , the problem remains.
And when I set problem_storage_root:/homr/hiyot/Github/judge/somedirdoesnotexist , 'OSError: Path is not a directory' occurs.

**Comment by Xyene** [comment]
In this case, what you'd actually want is `problem_storage_root: /home/hiyot/Github/judge`, or

```
problem_storage_root:
   - /home/hiyot/Github/problems
```

It's a bit confusing, and it's something we're thinking of redoing in the future, but that should work.

**Comment by hiyot** [comment]
1.I restart everything.
2.filetree
```
hiyot@hiyot-Lenovo:~/Github$ pwd
/home/hiyot/Github
hiyot@hiyot-Lenovo:~/Github$ tree problems
problems
└── aplusb
    ├── aplusb.zip
    └── init.json

1 directory, 2 files
hiyot@hiyot-Lenovo:~/Github$ tree judge/problems/
judge/problems/
└── aplusb
    ├── aplusb.zip
    └── init.json

1 directory, 2 files
```
3.problem_storage_root
```
# This is the same ID you specified in the judge admin panel
id: ExampleJudge
# The key this judge will use to authenticate with the site server, generated from the admin panel
key: "-t_qBN}_zr@WF_O(j>A]9:JR,-]@FMPN38(9Y:CDD]`ZT.|dYdH03q#;cN8?5s(gvu0LeSBMy3cc;06)pF)<nX]C=.Us^{#7w!9:"
# Where to look for problems on the local filesystem.
# This directory /not/ scanned recursively, and any directory containing an init.json file is assumed to
# be a problem directory.
problem_storage_root:
   - /home/hiyot/Github/problems
# All configuration for language executors
# If you're unsure of what values a language needs, your best bet is to consult the source of the executor:
# <https://github.com/DMOJ/judge/tree/master/executors>
runtime:
  ccl: /opt/ccl/lx86cl
  sed: /bin/sed
  awk: /usr/bin/awk
  gnatmake: /usr/bin/gnatmake
  chicken-csc: /usr/bin/csc
  dart: /opt/dart-sdk/bin/dart
  tclsh: /usr/bin/tclsh
  cobc: /usr/bin/cobc
  erl: /usr/bin/erl
  erlc: /usr/bin/erlc
  tprolog: /opt/turing/tprolog/tprolog
  tprologc: /opt/turing/tprolog/tprologc
  turing_dir: /opt/turing/tprolog
  node: /usr/bin/node
  lua: /usr/bin/lua
  ocaml: /usr/bin/ocamlopt
  pypy: /opt/pypy/bin/pypy
  pypydir: /opt/pypy/
  pypy3: /opt/pypy3/bin/pypy
  pypy3dir: /opt/pypy3/
  ghc: /usr/bin/ghc
  go: /usr/bin/go
  fsharpc: /usr/bin/fsharpc
  mono-csc: /usr/bin/mono-csc
  mono-vbnc: /usr/bin/vbnc
  mono: /usr/bin/mono
  dmd: /usr/bin/dmd
  fpc: /opt/fpc-2.6.4/bin/fpc
  clang: /usr/bin/clang
  clang++: /usr/bin/clang++
  gcc: /usr/bin/gcc
  g++: /usr/bin/g++
  g++11: /usr/bin/g++
  g++14: /opt/gcc-5.1.0/bin/g++
  gfortran: /usr/bin/gfortran
  nasm: /usr/bin/nasm
  ld: /usr/bin/ld
  python: /opt/python27/bin/python2.7
  python2dir: /opt/python27/
  python3: /opt/python34/bin/python3.4
  python3dir: /opt/python34/
  java: /usr/bin/java
  javac: /usr/bin/javac
  java8: /usr/lib/jvm/jdk-8-oracle-i586/bin/java
  javac8: /usr/lib/jvm/jdk-8-oracle-i586/bin/javac
# Custom V8 build to facilitate online judging: https://github.com/DMOJ/v8dmoj
  v8dmoj: /home/judge/judge/executors/v8dmoj
  php: /usr/bin/php
  phpconfdir: /etc/php5/
  perl: /usr/bin/perl
  ruby19: /usr/bin/ruby1.9.1
  ruby21: /usr/bin/ruby
  racket: /opt/racket/bin/racket
  raco: /opt/racket/bin/raco
  racket-lib: /opt/racket/lib
  gnustep-config: /usr/bin/gnustep-config
  gobjc: /usr/bin/gcc
```
4. init.json
```
hiyot@hiyot-Lenovo:~$ cat Github/judge/problems/aplusb/init.json 
{
    "archive": "aplusb.zip",
    "test_cases": [
        {
            "in": "aplusb.1.in",
            "out": "aplusb.1.out",
            "points": 5
        },
        {
            "in": "aplusb.2.in",
            "out": "aplusb.2.out",
            "points": 75
        },
        {
            "in": "aplusb.3.in",
            "out": "aplusb.3.out",
            "points": 20
        }
    ]
}

```
it doesn't work still.
:(((
