### ISSUE TITLE
Improvements to organizations

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#705]
Tracking issue for miscellaneous organization page improvements that should be done.

* Add confirmation dialog before allowing a kick
* Only show kick buttons when hovering over the row
```css
form.kick-form a.button {
    display: none;
}

tr:hover td > form.kick-form a.button {
    display: block;
}
```
* Do something about _Organization description not provided_
* more to come
