### ISSUE TITLE
@media queries for narrow screens

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#95]
We should use `@media` queries to restyle the interface for narrower screens.

For example:

```css
@media (max-width: 700px) {
  #navigation ul {display: none;}
  #user-links { display: block; height: 1.5em; width: 100%; max-width: none; position: static; vertical-align: bottom; text-align: right; padding-top: 0.25em; margin-right: 1em; }
  #statistics-table { display: none; }
  #fake-info-float { display: none; }
  #submissions-table { width: 100%; }
}
```

That's something I made in 5 minutes. If we spend a bit more effort we can easily make it look a lot nicer. We would need to convert the navigation `ul` into a hamburger menu though.

**Comment by quantum5** [comment]
@Xyene 2-level hamburger is not scary:

```css
#navigation ul { position: fixed; top: 0; background: black; bottom: 0; width:8em; padding: 0; left: 0}
#navigation ul li, #navigation ul li a {  display: block; }
#navigation ul li ul, #navigation ul li a { left: 8em }
```

**Comment by quantum5** [comment]
Hamburger button:

```html
<a id="navicon" class="fa fa-bars" href="javascript:void(0)"></a>
```

```css
#navicon {display: none}

@media (max-width: 700px) {
  #navigation {display: flex;}
  #navicon {display: block; line-height: 1em; font-size: 1.5em; color: white; padding-left: 0.2em}
  #nav-list { display: none }
  #navigation ul { position: fixed; top: 0; background: black; bottom: 0; width:8em; padding: 0; left: 0}
  #navigation ul li, #navigation ul li a {  display: block; }
  #navigation ul li ul { left: 8em; top: auto; bottom: auto; margin-top: -36px }
  #user-links { display: block; height: 1.5em; width: 100%; max-width: none; position: static; vertical-align: bottom; text-align: right; padding-top: 0.25em; margin-right: 1em; }
  #statistics-table { display: none; }
  #fake-info-float { display: none; }
  #submissions-table { width: 100%; }
}
```

```js
$('#navicon').click(function(event) {
    event.stopPropagation();
    $('#nav-list').show('slow');
    $('#nav-list').click(function(event){
        event.stopPropagation();
    });
    $('html').click(function() {
        $('#nav-list').hide('slow');
    });
});
```

**Comment by quantum5** [comment]
```css
@media (min-width: 701px) {
  #nav-list { display: block !important; }
}
```
is needed to for the nav to appear otherwise.
